
defaults: &defaults
  adapter: postgresql


development:
  <<: *defaults
  database: fred654_dev

test:
  <<: *defaults
  database: fred654_test


production:
  <<: *defaults
  database: fred4321_production
